# Generated by Django 2.0.7 on 2018-07-06 11:06

from django.db import migrations, models
import django.db.models.deletion
import media_guard.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('download_url', models.URLField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DownloadableFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=False)),
                ('file', models.FileField(storage=media_guard.storage.ProtectedFileSystemStorage(), upload_to='assets')),
                ('name', models.CharField(help_text='An internal name for the purposes of searching.', max_length=512)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_files', to='example.Asset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloadable_files', to='example.Asset')),
            ],
        ),
    ]
